---
words:
  - hotspots

ignoreWords:
  # Cursor
  - bugbot

  # shell
  - realpath

  # lang-rust
  - thiserror
  - rustdocflags

  # skills
  - glab
  - Gitea

  # names
  - rohde
  - schwarz

  # miscellaneous
  - sonarlint
  - sonarqube
