---
version: '0.2'

ignorePaths: []

dictionaries:
  - en_US
  - softwareTerms
  - bash

words:
  - agentic
  - backpressure
  - unsanitized

ignoreWords:
  # Python
  - pyproject
  - RORO

  # Rust
  - clippy
  - rustup
  - thiserror
